# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope.platform.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope.platform.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import get_events as get_events
from ecoscope.platform.tasks.io import (
    get_patrol_observations as get_patrol_observations,
)
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_point_layer as create_point_layer
from ecoscope.platform.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope.platform.tasks.transformation import filter_df as filter_df
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import sort_values as sort_values
from ecoscope.platform.tasks.transformation import with_unit as with_unit
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from wt_task import task

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_format="%d %b %Y %H:%M:%S", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params_dict.get("get_timezone") or {}))
        .call()
    )

    patrol_obs = (
        task(get_patrol_observations)
        .validate()
        .set_task_instance_id("patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            include_patrol_details=True,
            raise_on_empty=False,
            sub_page_size=None,
            **(params_dict.get("patrol_obs") or {}),
        )
        .call()
    )

    events_data = (
        task(get_events)
        .validate()
        .set_task_instance_id("events_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
            ],
            raise_on_empty=False,
            include_null_geometry=True,
            include_display_values=True,
            **(params_dict.get("events_data") or {}),
        )
        .call()
    )

    set_leaderboard_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_leaderboard_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Ranger Leaderboard", **(params_dict.get("set_leaderboard_title") or {})
        )
        .call()
    )

    set_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Patrols & Events Map", **(params_dict.get("set_map_title") or {}))
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("base_map_defs") or {}))
        .call()
    )

    convert_patrols_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrols_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs,
            timezone=get_timezone,
            columns=["patrol_start_time", "patrol_end_time", "fixtime"],
            **(params_dict.get("convert_patrols_tz") or {}),
        )
        .call()
    )

    patrol_reloc = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("patrol_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=convert_patrols_tz,
            relocs_columns=[
                "patrol_id",
                "patrol_start_time",
                "patrol_end_time",
                "patrol_type__value",
                "patrol_type__display",
                "patrol_serial_number",
                "patrol_status",
                "patrol_subject",
                "groupby_col",
                "fixtime",
                "junk_status",
                "extra__source",
                "geometry",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params_dict.get("patrol_reloc") or {}),
        )
        .call()
    )

    patrol_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=patrol_reloc, **(params_dict.get("patrol_traj") or {}))
        .call()
    )

    traj_rename_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("traj_rename_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_traj,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__patrol_subject": "patrol_subject",
                "extra__patrol_id": "patrol_id",
            },
            raise_if_not_found=True,
            **(params_dict.get("traj_rename_cols") or {}),
        )
        .call()
    )

    convert_events_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_data,
            timezone=get_timezone,
            columns=["time"],
            **(params_dict.get("convert_events_tz") or {}),
        )
        .call()
    )

    extract_reported_by = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_reported_by")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_tz,
            column_name="reported_by",
            field_name_options=["name"],
            output_type="str",
            output_column_name="reported_by_name",
            **(params_dict.get("extract_reported_by") or {}),
        )
        .call()
    )

    events_with_reporter = (
        task(filter_df)
        .validate()
        .set_task_instance_id("events_with_reporter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_reported_by,
            column_name="reported_by_name",
            op="ne",
            value="None",
            reset_index=True,
            **(params_dict.get("events_with_reporter") or {}),
        )
        .call()
    )

    patrol_summary = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("patrol_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_rename_cols,
            groupby_cols=["patrol_subject"],
            summary_params=[
                {
                    "display_name": "Patrol Count",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "Total Distance (km)",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                    "decimal_places": 1,
                },
                {
                    "display_name": "Total Duration (hrs)",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                    "decimal_places": 1,
                },
            ],
            reset_index=True,
            **(params_dict.get("patrol_summary") or {}),
        )
        .call()
    )

    patrol_summary_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("patrol_summary_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_summary,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"patrol_subject": "Ranger"},
            raise_if_not_found=True,
            **(params_dict.get("patrol_summary_rename") or {}),
        )
        .call()
    )

    event_summary = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("event_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_with_reporter,
            groupby_cols=["reported_by_name"],
            summary_params=[
                {"display_name": "Event Count", "aggregator": "count", "column": "id"}
            ],
            reset_index=True,
            **(params_dict.get("event_summary") or {}),
        )
        .call()
    )

    event_summary_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("event_summary_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=event_summary,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"reported_by_name": "Ranger"},
            raise_if_not_found=True,
            **(params_dict.get("event_summary_rename") or {}),
        )
        .call()
    )

    leaderboard_merge = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("leaderboard_merge")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=patrol_summary_rename,
            right=event_summary_rename,
            how="outer",
            on="Ranger",
            left_on=None,
            right_on=None,
            left_index=False,
            right_index=False,
            fillna_value=0,
            **(params_dict.get("leaderboard_merge") or {}),
        )
        .call()
    )

    leaderboard_sorted = (
        task(sort_values)
        .validate()
        .set_task_instance_id("leaderboard_sorted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=leaderboard_merge,
            column_name="Ranger",
            ascending=True,
            na_position="last",
            **(params_dict.get("leaderboard_sorted") or {}),
        )
        .call()
    )

    leaderboard_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("leaderboard_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=leaderboard_sorted,
            widget_id=set_leaderboard_title,
            columns=[
                "Ranger",
                "Patrol Count",
                "Total Distance (km)",
                "Total Duration (hrs)",
                "Event Count",
            ],
            table_config={
                "enable_sorting": True,
                "enable_filtering": False,
                "enable_download": True,
                "hide_header": False,
            },
            **(params_dict.get("leaderboard_table") or {}),
        )
        .call()
    )

    leaderboard_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("leaderboard_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=leaderboard_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="leaderboard",
            **(params_dict.get("leaderboard_table_html") or {}),
        )
        .call()
    )

    leaderboard_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("leaderboard_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_leaderboard_title,
            data=leaderboard_table_html,
            **(params_dict.get("leaderboard_table_widget") or {}),
        )
        .call()
    )

    total_patrols = (
        task(dataframe_column_nunique)
        .validate()
        .set_task_instance_id("total_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_rename_cols,
            column_name="patrol_id",
            **(params_dict.get("total_patrols") or {}),
        )
        .call()
    )

    total_patrols_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_patrols_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Patrols",
            data=total_patrols,
            decimal_places=0,
            **(params_dict.get("total_patrols_sv") or {}),
        )
        .call()
    )

    total_distance = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_distance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_rename_cols,
            column_name="dist_meters",
            **(params_dict.get("total_distance") or {}),
        )
        .call()
    )

    total_distance_km = (
        task(with_unit)
        .validate()
        .set_task_instance_id("total_distance_km")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            value=total_distance,
            original_unit="m",
            new_unit="km",
            **(params_dict.get("total_distance_km") or {}),
        )
        .call()
    )

    total_distance_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_distance_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Distance (km)",
            data=total_distance_km,
            decimal_places=1,
            **(params_dict.get("total_distance_sv") or {}),
        )
        .call()
    )

    total_duration = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_duration")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_rename_cols,
            column_name="timespan_seconds",
            **(params_dict.get("total_duration") or {}),
        )
        .call()
    )

    total_duration_hrs = (
        task(with_unit)
        .validate()
        .set_task_instance_id("total_duration_hrs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            value=total_duration,
            original_unit="s",
            new_unit="h",
            **(params_dict.get("total_duration_hrs") or {}),
        )
        .call()
    )

    total_duration_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_duration_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Duration (hrs)",
            data=total_duration_hrs,
            decimal_places=1,
            **(params_dict.get("total_duration_sv") or {}),
        )
        .call()
    )

    total_events = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=event_summary,
            column_name="Event Count",
            **(params_dict.get("total_events") or {}),
        )
        .call()
    )

    total_events_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_events_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Events",
            data=total_events,
            decimal_places=0,
            **(params_dict.get("total_events_sv") or {}),
        )
        .call()
    )

    events_filter = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("events_filter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_reported_by,
            roi_gdf=None,
            roi_name=None,
            reset_index=True,
            **(params_dict.get("events_filter") or {}),
        )
        .call()
    )

    events_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("events_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_filter,
            input_column_name="event_type",
            colormap="tab20b",
            output_column_name="event_type_colormap",
            **(params_dict.get("events_colormap") or {}),
        )
        .call()
    )

    events_display_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("events_display_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_colormap,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "serial_number": "Event Serial",
                "time": "Event Time",
                "event_type_display": "Event Type",
                "reported_by_name": "Reported By",
            },
            raise_if_not_found=False,
            **(params_dict.get("events_display_rename") or {}),
        )
        .call()
    )

    event_point_layer = (
        task(create_point_layer)
        .validate()
        .set_task_instance_id("event_point_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=events_display_rename,
            layer_style={"fill_color_column": "event_type_colormap", "get_radius": 5},
            legend={
                "label_column": "Event Type",
                "color_column": "event_type_colormap",
            },
            tooltip_columns=["Event Serial", "Event Time", "Event Type", "Reported By"],
            **(params_dict.get("event_point_layer") or {}),
        )
        .call()
    )

    traj_display_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("traj_display_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_rename_cols,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "patrol_subject": "Patrol Subject",
                "segment_start": "Start",
                "speed_kmhr": "Speed (kph)",
            },
            raise_if_not_found=False,
            **(params_dict.get("traj_display_rename") or {}),
        )
        .call()
    )

    traj_polyline_layer = (
        task(create_polyline_layer)
        .validate()
        .set_task_instance_id("traj_polyline_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=traj_display_rename,
            layer_style={
                "get_color": [80, 80, 80],
                "color_column": None,
                "get_width": 3,
                "width_units": "pixels",
                "cap_rounded": True,
                "opacity": 1,
            },
            legend=None,
            tooltip_columns=["Patrol Subject", "Start", "Speed (kph)"],
            **(params_dict.get("traj_polyline_layer") or {}),
        )
        .call()
    )

    map_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("map_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=[traj_polyline_layer, event_point_layer],
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Event Type",
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            widget_id=set_map_title,
            **(params_dict.get("map_ecomap") or {}),
        )
        .call()
    )

    map_ecomap_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("map_ecomap_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=map_ecomap,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ranger_map",
            **(params_dict.get("map_ecomap_html") or {}),
        )
        .call()
    )

    map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_map_title,
            data=map_ecomap_html,
            **(params_dict.get("map_widget") or {}),
        )
        .call()
    )

    ranger_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("ranger_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                total_patrols_sv,
                total_distance_sv,
                total_duration_sv,
                total_events_sv,
                leaderboard_table_widget,
                map_widget,
            ],
            time_range=time_range,
            **(params_dict.get("ranger_dashboard") or {}),
        )
        .call()
    )

    return ranger_dashboard
